### ISSUE TITLE
Plugin adds test dependencies to all modules

### ISSUE THREAD

**Issue by ennru** [maichler/sbt-jupiter-interface#24]
Adding this sbt plugin adds JUnit 4 (including Hamcrest) and JUnit 5 transitively to all projects in the build.
I believe it should be up to the user of the plugin to decide which JUnit versions to use in each (sub-)project, or at least the plugin should not be enabled on all projects by default.

**Comment by maichler** [comment]
Hi ennru,

you can use any version of JUnit 5 which is binary compatible to this plugins runtime library. For newer versions of JUnit just add a library dependency like this:

```
libraryDependencies += "org.junit.jupiter" % "junit-jupiter-engine" % "5.2.0" % "test"
```

The dependency to JUnit 4 gets pulled in by junit-platform-runner. If this is not what you want you could add an exclusion rule like this:

```
excludeDependencies += "junit" % "junit"
```

The plugin adds itself to all (sub-)projects which have the JVMPlugin enabled. You could disable the plugin for specific projects like this:

```
lazy val subProject = project.in(file("sub"))
  .disablePlugins(JupiterPlugin)
```

Does this help ?

**Comment by ennru** [comment]
Thank you for coming back on this.

I wonder what would be the best/least surprising behaviour. Its good convenience to have the plugin added to all projects in the build, but it might not be expected in all cases.

A way I'd prefer would be to require the projects to explicitly depend on the JUnit libraries (and possibly activate the plugin if there is JUnit on the classpath).

**Comment by ennru** [comment]
I believe dependency management is very hard, and every dependency (even in test scopes) is a liability.
Letting a plugin silently pull in these dependencies does not go well together with my "panic" for dependencies:
```
[info] sbt-jupiter-junit4:sbt-jupiter-junit4_2.12:0.1.0-SNAPSHOT [S]
[info]   +-net.aichler:jupiter-interface:0.7.0
[info]     +-org.junit.jupiter:junit-jupiter-engine:5.1.0
[info]     | +-org.apiguardian:apiguardian-api:1.0.0
[info]     | +-org.junit.jupiter:junit-jupiter-api:5.1.0
[info]     | | +-org.apiguardian:apiguardian-api:1.0.0
[info]     | | +-org.junit.platform:junit-platform-commons:1.1.0
[info]     | | | +-org.apiguardian:apiguardian-api:1.0.0
[info]     | | |
[info]     | | +-org.opentest4j:opentest4j:1.0.0
[info]     | |
[info]     | +-org.junit.platform:junit-platform-engine:1.1.0
[info]     |   +-org.apiguardian:apiguardian-api:1.0.0
[info]     |   +-org.junit.platform:junit-platform-commons:1.1.0
[info]     |   | +-org.apiguardian:apiguardian-api:1.0.0
[info]     |   |
[info]     |   +-org.opentest4j:opentest4j:1.0.0
[info]     |
[info]     +-org.junit.platform:junit-platform-runner:1.1.0
[info]     | +-junit:junit:4.12
[info]     | | +-org.hamcrest:hamcrest-core:1.3
[info]     | |
[info]     | +-org.apiguardian:apiguardian-api:1.0.0
[info]     | +-org.junit.platform:junit-platform-launcher:1.1.0
[info]     | | +-org.apiguardian:apiguardian-api:1.0.0
[info]     | | +-org.junit.platform:junit-platform-engine:1.1.0
[info]     | |   +-org.apiguardian:apiguardian-api:1.0.0
[info]     | |   +-org.junit.platform:junit-platform-commons:1.1.0
[info]     | |   | +-org.apiguardian:apiguardian-api:1.0.0
[info]     | |   |
[info]     | |   +-org.opentest4j:opentest4j:1.0.0
[info]     | |
[info]     | +-org.junit.platform:junit-platform-suite-api:1.1.0
[info]     |   +-org.apiguardian:apiguardian-api:1.0.0
[info]     |   +-org.junit.platform:junit-platform-commons:1.1.0
[info]     |     +-org.apiguardian:apiguardian-api:1.0.0
[info]     |
[info]     +-org.scala-sbt:test-interface:1.0
```

The only dependencies I want my test code to have would be `org.junit.jupiter  % junit-jupiter-api % 5.1.0` and its transitive dependencies. 
And I'd preferable depend explicitly on it, maybe via a plugin-provided setting key.

**Comment by maichler** [comment]
Thank you for the clarification!

I can see where you're coming from and I think it's totally valid (to a certain degree - if you carried this to the limit you'd end up with no (automatic) dependency management at all). 

The dependency tree looks like an awful lot which is mainly due to the modular nature of JUnit 5. Take the dependency tree of `junit-interface` for example:

```
> test:dependencyTree
[info] sbt-jupiter-junit4:sbt-jupiter-junit4_2.10:0.1-SNAPSHOT [S]
[info]   +-com.novocode:junit-interface:0.11
[info]   | +-junit:junit:4.11 (evicted by: 4.12)
[info]   | +-junit:junit:4.12
[info]   | | +-org.hamcrest:hamcrest-core:1.3
[info]   | | 
[info]   | +-org.scala-sbt:test-interface:1.0
[info]   | 
[info]   +-junit:junit:4.12
[info]   | +-org.hamcrest:hamcrest-core:1.3
```

The only difference is that `junit:junit:4.12` contains everything (api, runner, ...). The only optional dependency is hamcrest.

`jupiter-interface` is for `JUnit 5` what `junit-interface` is for `JUnit 4`. 

It provides an implementation of `sbt.testing.Framework` which is able to identify and run test classes using the `JUnit 5 API`. For this to work `jupiter-interface` needs to be on a projects test-classpath since SBT silently ignores tests if it can't find the related test framework (in this case `net.aichler.jupiter.api.JupiterFramework`).

For the compilation to succeed `junit-jupiter-api` needs to be on the classpath as well. A dependency to `junit-jupiter-engine` and `junit-platform-launcher` is required to finally run the tests.

Without `junit-jupiter-engine` executing test fails with the following error:

```
[error] (test:definedTests) org.junit.platform.commons.util.PreconditionViolation
Exception: Cannot create Launcher without at least one TestEngine; consider adding 
an engine implementation JAR to the classpath
```

Without `junit-platform-launcher` executing `test` fails with the following error:

```
[error] Could not run test testpackage.Junit5Test: java.lang.NoClassDefFoundError: 
org/junit/platform/launcher/TestExecutionListener
```

Thanks to this exercise I now realize we've got rid of the dependency to `junit-platform-runner`:

```
[info] sbt-jupiter-junit4:sbt-jupiter-junit4_2.10:0.1-SNAPSHOT [S]
[info]   +-net.aichler:jupiter-interface:0.7.1-SNAPSHOT
[info]   | +-org.scala-sbt:test-interface:1.0
[info]   | 
[info]   +-org.junit.jupiter:junit-jupiter-api:5.1.0
[info]   | +-org.apiguardian:apiguardian-api:1.0.0
[info]   | +-org.junit.platform:junit-platform-commons:1.1.0
[info]   | | +-org.apiguardian:apiguardian-api:1.0.0
[info]   | | 
[info]   | +-org.opentest4j:opentest4j:1.0.0
[info]   | 
[info]   +-org.junit.jupiter:junit-jupiter-engine:5.1.0
[info]   | +-org.apiguardian:apiguardian-api:1.0.0
[info]   | +-org.junit.jupiter:junit-jupiter-api:5.1.0
[info]   | | +-org.apiguardian:apiguardian-api:1.0.0
[info]   | | +-org.junit.platform:junit-platform-commons:1.1.0
[info]   | | | +-org.apiguardian:apiguardian-api:1.0.0
[info]   | | | 
[info]   | | +-org.opentest4j:opentest4j:1.0.0
[info]   | | 
[info]   | +-org.junit.platform:junit-platform-engine:1.1.0
[info]   |   +-org.apiguardian:apiguardian-api:1.0.0
[info]   |   +-org.junit.platform:junit-platform-commons:1.1.0
[info]   |   | +-org.apiguardian:apiguardian-api:1.0.0
[info]   |   | 
[info]   |   +-org.opentest4j:opentest4j:1.0.0
[info]   |   
[info]   +-org.junit.platform:junit-platform-launcher:1.1.0
[info]     +-org.apiguardian:apiguardian-api:1.0.0
[info]     +-org.junit.platform:junit-platform-engine:1.1.0
[info]       +-org.apiguardian:apiguardian-api:1.0.0
[info]       +-org.junit.platform:junit-platform-commons:1.1.0
[info]       | +-org.apiguardian:apiguardian-api:1.0.0
[info]       | 
[info]       +-org.opentest4j:opentest4j:1.0.0
```

Still far away from a dependency tree of only `junit-jupiter-api` but the best we can do, I'm afraid. 

I need to think more about how to decouple the plugin from the library.

**Comment by maichler** [comment]
@ennru The runtime library now needs to be added to every project which wants to run JUnit 5 tests. An exception is triggered when there are JUnit 5 tests but the runtime has not been added as test dependency (prevents SBT to silently ignore those tests). 

I did not remove transitive dependencies of the runtime library since this can be easily controlled when adding the runtime library (notTransitive, exclude, etc).

What do you think ?

**Comment by maichler** [comment]
I forgot to mention that the changes were committed to branch `ticket-24`

**Comment by maichler** [comment]
With those changes it's now as close to `junit-interface` as possible - you just need to add the library dependency to every project which wants to run tests with JUnit 5.

The only difference is that for JUnit 5 you also have to add the SBT plugin - there's IMHO no way around it. The plugin registers `jupiter-interface` as additional test framework. And since SBT filters `package private` classes and methods by default the plugin also adds JUnit Jupiters test discovery mechanism so that SBT is able to find tests at all. 

I think adding the runtime library to projects instead of explicitly enabling the plugin is better 

* transitive dependencies are easily controllable
* dependency update mechanism can be made faster by moving the runtime library dependency into a common subproject
* the plugin is enabled by default and can therefore warn if there are JUnit 5 tests but no runtime library. This is much better than SBT silently ignoring those tests and report a successful test run

**Comment by ennru** [comment]
Ok, I agree. These are good reasons to go down this road. I'm almost ready to push a PR using your plugin for [Alpakka Kafka](https://github.com/akka/alpakka-kafka).

**Comment by maichler** [comment]
Cool, I'm going to roll a new release then !

**Comment by maichler** [comment]
Thank you for contributing !

**Comment by dwijnand** [comment]
An alternative approach is having a build-wide setting to toggle the behaviour of adding the runtime library.

That way it's only 1 key that needs modifying to affect the whole build.

**Comment by maichler** [comment]
@dwijnand  A build-wide setting is available, already. Just add the runtime library as dependency to the root project in scope `ThisBuild`. This way you have control over the specific runtime version and its transitive dependencies. And I think it also performs better in multi-project scenarios when dependencies are updated by `SBT`.

```
libraryDependencies in ThisBuild +=  "net.aichler" % "jupiter-interface" % "0.8.0" % Test
```

Does this make sense ?

**Comment by dwijnand** [comment]
One of the difficult decisions as the author of an sbt plugin is deciding if your plugin will auto-trigger or if it requires manual steps, like enabling a plugin or in this case adding another dependency.

I'm still not sure which default I prefer and if there's a good guiding principle to use.  The closest I've heard (IIRC) is https://github.com/sjrd saying that sbt plugins shouldn't auto-trigger if they modify default sbt behaviour.

Now, _adding_ a dependency is a bit more subtle.  I'd generally think it's ok, but I can understand @ennru's needs.

So as the sbt author you must decide whether you want to support Enno's use case out the box, and for that you can indeed use `libraryDependencies in ThisBuild` (I'd suggest adding that to the README).

But if you decide instead that Enno's use case is the exception and you want to go back to auto-adding the library, then you could satisfy Enno's needs by providing a build-wide key to opt-out of adding the runtime library.  So something like:

```scala
junitJunipterAddRuntime in ThisBuild := false
```

That would be nicer than having to do something along the lines of:

```scala
libraryDependencies in ThisBuild ~= (deps => /* filter out dep with organization net.aichler and name jupiter-interface */)
```

By the way, just sharing thoughts and ideas, I'm not making any requests 😄

**Comment by maichler** [comment]
> So as the sbt author you must decide whether you want to support Enno's use case out the box, and for that you can indeed use libraryDependencies in ThisBuild (I'd suggest adding that to the README).

Thank you for the suggestion - totally forgot about adding a note to the README, will do ASAP !

I think that the new default behaviour is a real improvement, although it took me half through the discussion to reach that conclusion ;) 

Thanks !
