### ISSUE TITLE
Run test under another folder than test is not working

### ISSUE THREAD

**Issue by GregoryBevan** [maichler/sbt-jupiter-interface#35]
Hi,

I'm not pretty sure the problem I'm going to describe is due to _jupiter-interface_, but things gone well before migrating from JUnit 4 to JUnit 5.

In our project, we have two tests folders, the first one for unit test and the other for integration tests. Sbt has been configured to handle these two folders, but when I run the following command, `sbt it:test`, no tests are launched. 

I've tried different sbt configuration without success, and I think maybe the jupiter launcher doesn't take the _it-classes_ folder in its classloader for test scanning.

I have a sample project to reproduce the problem, [junit5-sbt](https://github.com/GregoryBevan/junit5_sbt).

Thank you for your help even if you think the problem is not coming from your plugin.

**Comment by maichler** [comment]
Hi,

it could be a classloading issue, I will look into it asap. 

Thank you for providing such a detailed  description !

**Comment by maichler** [comment]
@GregoryBevan Problem is that plugin specific tasks get not added to your custom configuration. PR #36 makes JupiterPlugin.scopedSettings public so that it can be accessed. Could you please test with a local build from branch `wip-ticket-36` (`publishLocal` and then reference version `0.8.2-SNAPSHOT` in your project). 

There are new test cases in `src/plugin/sbt-test/basic`, `finds-test-from-extended-config` and `finds-test-from-it-config` which you can use as reference. 

Thx!

**Comment by GregoryBevan** [comment]
Thank you for your work. I could only test it on monday, not at work today.

**Comment by maichler** [comment]
That's fine with me, thank you!

**Comment by GregoryBevan** [comment]
Hi Michael,

I've just tried to run integration tests with the last snapshot version, and it works.

Thank you

**Comment by maichler** [comment]
Great !

Then I'm going to merge #36 and release another version.

**Comment by GregoryBevan** [comment]
Thank you for the fast release. I'm going to use it right now.

**Comment by maichler** [comment]
Binaries for 0.8.2 should be available now.
